### PR TITLE
[Docs] Add initial documentation, currently empty

### PR DESCRIPTION
**Pull request by dimakuv**
The documentation source files are taken from the main Graphene repo.

Signed-off-by: Dmitrii Kuvaiskii <dmitrii.kuvaiskii@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)

### CODE REVIEW

**Review by mkow — DISMISSED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[Documentation/conf.py, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkkl219x_E9DjTiKku:-Mbkkl219x_E9DjTiKkv:bjsog2j) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L23)):*
> ```Python
> import subprocess
> 
> import recommonmark.parser
> ```

recommonmark was transitional for old wiki on github, which was copied as-is and then reformatted article-by-article. We don't want to have new documents in markdown.
___
*[Documentation/conf.py, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkxNGEu_DyxUT4zYA:-MbkkxNGEu_DyxUT4zYB:b-1p2xe5) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L50)):*
> ```Python
>     'sphinx.ext.todo',
>     'breathe',
>     'recommonmark',
> ```

-recommonmark
___
*[Documentation/conf.py, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkzPV6_-CIj1AN2GX:-MbkkzPV6_-CIj1AN2GY:b-gmx8i1) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L61)):*
> ```Python
>     '.rst': 'restructuredtext',
>     '.md': 'markdown',
>     '.markdown': 'markdown',
> ```

-markdown (2 lines)
___
*[Documentation/conf.py, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkl5FB057Q96dc_7L4:-Mbkl5FB057Q96dc_7L5:bqlfowa) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L94)):*
> ```Python
> def generate_doxygen(app):
>     for p in breathe_projects:
>         subprocess.check_call(['doxygen', 'Doxyfile-{}'.format(p)])
> ```

Someone someday will be surprised by this. If you don't need multiple doxygen files, I think we can have single Doxygen files and just `check_call(['doxygen', 'Doxyfile'])`.

(We needed many Doxygen files in graphene at least when I was doing this, because there were multiple files with same names and that's wrong for doxygen).
___
*[Documentation/Doxyfile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbknn9K1GhpmGmJvJIQ:-Mbknn9L2sihYLyQItmI:b5zv1dh) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/Doxyfile#L1)):*
> ```
> # This is a common Doxyfile, actual listings are built from Doxyfile-*
> ```

See comment in `conf.py` about multiple Doxygen files.
___
*[Documentation/index.rst, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkjz46DocLbkL223Of:-Mbkjz46DocLbkL223Og:b-1u0odp) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/index.rst#L9)):*
> ```reStructuredText
> 
> This repository contains external contributions (like useful scripts, snippets,
> etc.) for `Graphene Project <https://github.com/oscarlab/graphene/>`_.
> ```

Double underscode `__` at the end. With single underscore, you can't have two links with the same URI.
___
*[Documentation/index.rst, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkACK0vTfqgat1nc4:-MbkkACK0vTfqgat1nc5:bb7c6g5) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/index.rst#L22)):*
> ```reStructuredText
> We welcome contributions through GitHub pull requests. Please keep in mind that
> they are governed by `the same rules as the main project
> <https://graphene.readthedocs.io/en/latest/devel/contributing.html>`_, modulo
> ```

`__`
___
*[Documentation/requirements.txt, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkGpa4aXl4u8v7yIn:-MbkkGpa4aXl4u8v7yIo:b-1p2xe5) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/requirements.txt#L3)):*
> ```vimhelp
> sphinx==1.8.0
> breathe<4.13.0
> recommonmark
> ```

-recommonmark

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: 8 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/conf.py, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkkl219x_E9DjTiKku:-MbkuTDa001Ar2MEyskW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L23)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

recommonmark was transitional for old wiki on github, which was copied as-is and then reformatted article-by-article. We don't want to have new documents in markdown.
</blockquote></details>

Done.
___
*[Documentation/conf.py, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkxNGEu_DyxUT4zYA:-MbkuVWu5_ulu0GtpmDh:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L50)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

-recommonmark
</blockquote></details>

Done.
___
*[Documentation/conf.py, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkzPV6_-CIj1AN2GX:-MbkuXZO3qlpRfH9tJhH:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L61)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

-markdown (2 lines)
</blockquote></details>

Done.
___
*[Documentation/conf.py, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkl5FB057Q96dc_7L4:-MbkudiK6Troltx3V2OZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L94)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Someone someday will be surprised by this. If you don't need multiple doxygen files, I think we can have single Doxygen files and just `check_call(['doxygen', 'Doxyfile'])`.

(We needed many Doxygen files in graphene at least when I was doing this, because there were multiple files with same names and that's wrong for doxygen).
</blockquote></details>

Done.
___
*[Documentation/Doxyfile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbknn9K1GhpmGmJvJIQ:-MbkugnG2sBtFLOHC31Y:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/Doxyfile#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

See comment in `conf.py` about multiple Doxygen files.
</blockquote></details>

Done.
___
*[Documentation/index.rst, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkjz46DocLbkL223Of:-MbkujUg664GdeZ6Xjyg:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/index.rst#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Double underscode `__` at the end. With single underscore, you can't have two links with the same URI.
</blockquote></details>

Done.
___
*[Documentation/index.rst, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkACK0vTfqgat1nc4:-MbkuleZBO2I8eVfpMji:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/index.rst#L22)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`__`
</blockquote></details>

Done.
___
*[Documentation/requirements.txt, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-MbkkGpa4aXl4u8v7yIn:-MbkuofIEdDfq8an9Wxp:b-896fix) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/requirements.txt#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

-recommonmark
</blockquote></details>

Done.

**Review by mkow — DISMISSED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/conf.py, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkl5FB057Q96dc_7L4:-MbkywypDmzgu-56vBD5:b-jiza7e) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```python
breathe_projects = {
    'graphene-contrib': '_build/doxygen/xml`,
}
```
And `for p in ...` is unnecessary.
___
*[Documentation/Doxyfile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbknn9K1GhpmGmJvJIQ:-Mbkz7XG6CpOkJf1Sa7y:bcpvx1l) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/Doxyfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Umm, I wasn't precise enough. You need to copy some variables from `Doxygen-*` files for this to work. At least:
```
PROJECT_NAME = "graphene-contrib"
OUTPUT_DIRECTORY = _build/doxygen # should match breathe_projects in conf.py
INPUT = ../src # or include/, or another directory where source files will be? IDK
```

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: 10 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/conf.py, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbkl5FB057Q96dc_7L4:-Mbl48fXEzAU68PPrmQ6:b-bwicf7) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/conf.py#L94)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```python
breathe_projects = {
    'graphene-contrib': '_build/doxygen/xml`,
}
```
And `for p in ...` is unnecessary.
</blockquote></details>

Done. I hope I understood you right.
___
*[Documentation/Doxyfile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbknn9K1GhpmGmJvJIQ:-Mbl4aX4BKQJlBWOhLzE:bv2tzyi) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/Doxyfile#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Umm, I wasn't precise enough. You need to copy some variables from `Doxygen-*` files for this to work. At least:
```
PROJECT_NAME = "graphene-contrib"
OUTPUT_DIRECTORY = _build/doxygen # should match breathe_projects in conf.py
INPUT = ../src # or include/, or another directory where source files will be? IDK
```
</blockquote></details>

Done. Let's keep `../src` for now, we'll change this later if needed.

**Review by woju — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Documentation/Doxyfile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-contrib/3#-Mbknn9K1GhpmGmJvJIQ:-Mbl8U4b7Tp9zR6hFwOZ:b-80tlqk) ([raw file](https://github.com/oscarlab/graphene-contrib/blob/09bf40b6a54ee45055abb3af3dce59f9b19fdc23/Documentation/Doxyfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Let's keep `../src` for now, we'll change this later if needed.
</blockquote></details>

Sure.

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-contrib/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
